version: '3'

services:

  3min_nextcloud_db:
    image: mariadb:latest
    container_name: 3min_nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
     - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
 
  3min_nextcloud_app:
    image: nextcloud
    depends_on:
      - 3min_nextcloud_db
    container_name: 3min_nextcloud_app
    restart: always
    ports:
     - 8889:80
    links:
     - 3min_nextcloud_db
    volumes:
     - ./data:/var/www/html
    environment:
      - MYSQL_HOST=3min_nextcloud_db
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}

volumes:
  data:
